prometheusOperator:
  image:
    repository: carlosedp/prometheus-operator
    tag: v0.26.0
  configmapReloadImage:
    repository: carlosedp/configmap-reload
    tag: v0.2.2
  prometheusConfigReloaderImage:
    repository: carlosedp/prometheus-config-reloader
    tag: v0.26.0
  hyperkubeImage:
    repository: gcr.io/google-containers/hyperkube-arm
    tag: v1.13.0
prometheus:
  prometheusSpec:
    image:
      repository: carlosedp/prometheus
      tag: v2.6.0
    storageSpec:
      class: ""
      selector:
        matchLabels:
          app: prometheus
      resources: {}
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 50Gi
        selector:
          matchLabels:
            app: prometheus
alertmanager:
  alertmanagerSpec:
    image:
      repository: carlosedp/alertmanager
      tag: v0.15.3
    storage:
      class: ""
      selector:
        matchLabels:
          app: alertmanager
      resources: {}
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
        selector:
          matchLabels:
            app: alertmanager
  config:
    global:
      smtp_smarthost: smtp.mailgun.org:587
      smtp_from: "Prometheus Alerting <alertmanager@devops.pistack.io>"
      smtp_auth_username: alertmanager@devops.pistack.io
    route:
      receiver: default
      routes:
      - receiver: default
        match:
          alertname: DeadMansSwitch
    receivers:
    - name: default
      email_configs:
      - to: alerts@devops.pistack.io
kubelet:
  serviceMonitor:
    https: true
kubeControllerManager:
  service:
    selector:
      k8s-app: null
      component: kube-controller-manager
kubeScheduler:
  service:
    selector:
      k8s-app: null
      component: kube-scheduler
coreDns:
  service:
    selector:
      k8s-app: kube-dns
kubeEtcd:
  service:
    port: 2379
    targetPort: 2379
    selector:
      k8s-app: null
      component: etcd
  serviceMonitor:
    scheme: https
grafana:
  enabled: false
  image:
    repository: carlosedp/monitoring-grafana
    tag: v5.4.2
kube-state-metrics:
  image:
    repository: carlosedp/kube-state-metrics
    tag: v1.4.0
prometheus-node-exporter:
  image:
    repository: carlosedp/node_exporter
    tag: v0.17.0